import { CONTRACT_FUNDING_STATUS } from "@/shared/constants/statuses";
import { formatStatus } from "@/shared/utils/job";
import { formatContractDateTime } from "./contractDetailUtils";

export function ContractOverviewSection({
  canGenerateVisitOtp,
  canVerifyVisitOtp,
  contract,
  freelancerRejectedContract,
  handleGenerateVisitOtp,
  handleVerifyVisitOtp,
  isPending,
  remainingFundedBalance,
  setVisitOtp,
  visitOtp,
}) {
  return (
    <>
      <div className="grid gap-4 mb-6">
        <div>
          <strong>Contract type:</strong> {formatStatus(contract.contractType)}
        </div>
        <div>
          <strong>Total contract value:</strong> {contract.currency || "NPR"}{" "}
          {Number(contract.totalAmount || 0).toLocaleString()}
        </div>
        <div>
          <strong>Funding status:</strong>{" "}
          {formatStatus(
            contract.fundingStatus || CONTRACT_FUNDING_STATUS.UNFUNDED,
          )}
        </div>
        <div>
          <strong>Funded amount:</strong> {contract.currency || "NPR"}{" "}
          {Number(contract.fundedAmount || 0).toLocaleString()}
        </div>
        <div>
          <strong>Released amount:</strong> {contract.currency || "NPR"}{" "}
          {Number(contract.releasedAmount || 0).toLocaleString()}
        </div>
        <div>
          <strong>Refunded amount:</strong> {contract.currency || "NPR"}{" "}
          {Number(contract.refundedAmount || 0).toLocaleString()}
        </div>
        <div>
          <strong>Still held:</strong> {contract.currency || "NPR"}{" "}
          {Number(remainingFundedBalance || 0).toLocaleString()}
        </div>
        {contract.job?.budget ? (
          <div>
            <strong>Original job budget:</strong>{" "}
            {contract.job.budget.currency || "NPR"}{" "}
            {Number(contract.job.budget.min || 0).toLocaleString()}
            {contract.job.budget.max
              ? ` - ${contract.job.budget.currency || "NPR"} ${Number(contract.job.budget.max).toLocaleString()}`
              : ""}
          </div>
        ) : null}
        <div>
          <strong>Client signed:</strong>{" "}
          {contract.clientSignature?.signedAt ? "Yes" : "No"}
        </div>
        <div>
          <strong>Freelancer signed:</strong>{" "}
          {contract.freelancerSignature?.signedAt ? "Yes" : "No"}
        </div>
        {contract.freelancerSignature?.rejectedAt ? (
          <div>
            <strong>Freelancer requested changes:</strong>{" "}
            {formatContractDateTime(contract.freelancerSignature.rejectedAt)}
          </div>
        ) : null}
        {contract.completedAt ? (
          <div>
            <strong>Completed at:</strong>{" "}
            {formatContractDateTime(contract.completedAt)}
          </div>
        ) : null}
      </div>

      {contract.description ? (
        <div className="mb-6">
          <h3 className="mb-2">Scope</h3>
          <p className="text-secondary mb-0">{contract.description}</p>
        </div>
      ) : null}

      {contract.terms ? (
        <div className="mb-6">
          <h3 className="mb-2">Terms</h3>
          <p className="text-secondary mb-0">{contract.terms}</p>
        </div>
      ) : null}

      {contract.serviceMode === "physical" ? (
        <div className="mb-6">
          <h3 className="mb-2">Physical Visit Verification</h3>
          <div className="card-sm">
            <div
              className="card-sm"
              style={{
                marginBottom: "var(--space-3)",
                background:
                  "color-mix(in srgb, var(--color-primary) 7%, white)",
              }}
            >
              <strong>Before starting work</strong>
              <p className="text-secondary mb-0" style={{ marginTop: "var(--space-2)" }}>
                Please talk with the other party first in chat, confirm the site
                visit, and only after the visit enter the OTP generated by the
                client. Work should begin after that verification step is
                complete.
              </p>
            </div>
            <p className="text-secondary">
              <strong>Visit required:</strong>{" "}
              {contract.physicalVisit?.isRequired ? "Yes" : "No"}
            </p>
            {contract.physicalVisit?.preferredVisitDate ? (
              <p className="text-secondary">
                <strong>Preferred visit date:</strong>{" "}
                {new Date(contract.physicalVisit.preferredVisitDate).toLocaleDateString(
                  "en-NP",
                )}
              </p>
            ) : null}
            {contract.physicalVisit?.preferredWorkDate ? (
              <p className="text-secondary">
                <strong>Preferred work date:</strong>{" "}
                {new Date(contract.physicalVisit.preferredWorkDate).toLocaleDateString(
                  "en-NP",
                )}
              </p>
            ) : null}
            {contract.physicalVisit?.inspectionSummary ? (
              <p className="text-secondary">
                <strong>Inspection summary:</strong>{" "}
                {contract.physicalVisit.inspectionSummary}
              </p>
            ) : null}
            {contract.physicalVisit?.materialsAgreement ? (
              <p className="text-secondary">
                <strong>Materials agreement:</strong>{" "}
                {contract.physicalVisit.materialsAgreement}
              </p>
            ) : null}
            <p className="text-secondary mb-3">
              <strong>OTP status:</strong>{" "}
              {contract.physicalVisit?.verification?.status || "NOT_REQUIRED"}
            </p>
            {contract.booking ? (
              <p className="text-secondary">
                This verification was completed during the physical booking
                before contract signing.
              </p>
            ) : null}
            {canGenerateVisitOtp ? (
              <div className="flex gap-3 flex-wrap">
                <button
                  type="button"
                  className="btn btn-secondary btn-sm"
                  onClick={handleGenerateVisitOtp}
                  disabled={isPending}
                >
                  {isPending ? "Generating..." : "Generate On-site OTP"}
                </button>
                {contract.physicalVisit?.verification?.otpCode ? (
                  <span className="badge badge-warning">
                    OTP: {contract.physicalVisit.verification.otpCode}
                  </span>
                ) : null}
              </div>
            ) : null}
            {canVerifyVisitOtp ? (
              <div style={{ marginTop: "var(--space-3)" }}>
                <label className="form-label" htmlFor="visit-otp">
                  Enter client OTP
                </label>
                <div className="flex gap-3 flex-wrap">
                  <input
                    id="visit-otp"
                    className="form-input"
                    value={visitOtp}
                    onChange={(event) => setVisitOtp(event.target.value)}
                    placeholder="6-digit OTP"
                    style={{ maxWidth: "220px" }}
                  />
                  <button
                    type="button"
                    className="btn btn-primary btn-sm"
                    onClick={handleVerifyVisitOtp}
                    disabled={isPending || !visitOtp}
                  >
                    {isPending ? "Verifying..." : "Verify Visit"}
                  </button>
                </div>
              </div>
            ) : null}
            {contract.physicalVisit?.verification?.verifiedAt ? (
              <p className="text-secondary mb-0" style={{ marginTop: "var(--space-3)" }}>
                Verified at{" "}
                {formatContractDateTime(contract.physicalVisit.verification.verifiedAt)}
              </p>
            ) : null}
          </div>
        </div>
      ) : null}

      {freelancerRejectedContract ? (
        <div className="card-sm mb-6">
          <div className="flex items-center gap-3 flex-wrap mb-2">
            <span className="badge">Revision Requested</span>
            <span className="text-sm text-muted">
              {formatContractDateTime(contract.freelancerSignature.rejectedAt)}
            </span>
          </div>
          <p className="text-secondary mb-0">
            {contract.freelancerSignature.rejectionReason ||
              "The freelancer rejected the current draft. The proposal is still active, and the client can edit this contract and resend it."}
          </p>
        </div>
      ) : null}
    </>
  );
}
