export const JOB_CATEGORIES = [
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "Graphic Design",
  "Content Writing",
  "Digital Marketing",
  "Video Editing",
  "Data Entry",
  "Accounting & Finance",
  "Translation",
  "Photography",
  "Tutoring",
  "Plumbing",
  "Electrical",
  "Carpentry",
  "Cleaning",
  "Delivery",
  "Event Planning",
  "Other",
];

export const EXPERIENCE_LEVELS = [
  { value: "entry", label: "Entry Level" },
  { value: "intermediate", label: "Intermediate" },
  { value: "expert", label: "Expert" },
];

export const NEPAL_PROVINCES = [
  "Bagmati",
  "Gandaki",
  "Karnali",
  "Koshi",
  "Lumbini",
  "Madhesh",
  "Sudurpashchim",
];

export const NEPAL_DISTRICTS = [
  "Achham",
  "Arghakhanchi",
  "Baglung",
  "Baitadi",
  "Bajhang",
  "Bajura",
  "Banke",
  "Bara",
  "Bardiya",
  "Bhaktapur",
  "Bhojpur",
  "Chitwan",
  "Dadeldhura",
  "Dailekh",
  "Dang",
  "Darchula",
  "Dhading",
  "Dhankuta",
  "Dhanusha",
  "Dolakha",
  "Dolpa",
  "Doti",
  "Eastern Rukum",
  "Gorkha",
  "Gulmi",
  "Humla",
  "Ilam",
  "Jajarkot",
  "Jhapa",
  "Jumla",
  "Kailali",
  "Kalikot",
  "Kanchanpur",
  "Kapilvastu",
  "Kaski",
  "Kathmandu",
  "Kavrepalanchok",
  "Khotang",
  "Lalitpur",
  "Lamjung",
  "Mahottari",
  "Makwanpur",
  "Manang",
  "Morang",
  "Mugu",
  "Mustang",
  "Myagdi",
  "Nawalpur",
  "Nuwakot",
  "Okhaldhunga",
  "Palpa",
  "Panchthar",
  "Parasi",
  "Parbat",
  "Parsa",
  "Pyuthan",
  "Ramechhap",
  "Rasuwa",
  "Rautahat",
  "Rolpa",
  "Rupandehi",
  "Salyan",
  "Sankhuwasabha",
  "Saptari",
  "Sarlahi",
  "Sindhuli",
  "Sindhupalchok",
  "Siraha",
  "Solukhumbu",
  "Sunsari",
  "Surkhet",
  "Syangja",
  "Tanahun",
  "Taplejung",
  "Terhathum",
  "Udayapur",
  "Western Rukum",
];

export const NEPAL_CITIES = [
  "Bhadrapur",
  "Bhaktapur",
  "Bharatpur",
  "Bhimeshwar",
  "Biratnagar",
  "Birendranagar",
  "Birgunj",
  "Birtamod",
  "Butwal",
  "Damak",
  "Dhangadhi",
  "Dharan",
  "Gaur",
  "Ghorahi",
  "Godawari",
  "Hetauda",
  "Ithari",
  "Janakpur",
  "Kalaiya",
  "Kanchanrup",
  "Kapilvastu",
  "Kathmandu",
  "Kirtipur",
  "Lahan",
  "Lalitpur",
  "Lekhnath",
  "Madhyapur Thimi",
  "Mechinagar",
  "Nepalgunj",
  "Panauti",
  "Pokhara",
  "Putalibazar",
  "Rajbiraj",
  "Ramgram",
  "Siddharthanagar",
  "Tansen",
  "Tikapur",
  "Tokha",
  "Triyuga",
  "Tulsipur",
];

export const PROPERTY_TYPES = [
  "Apartment",
  "House",
  "Office",
  "Shop",
  "Restaurant",
  "Warehouse",
  "School",
  "Hospital",
  "Hotel",
  "Construction Site",
  "Land / Plot",
  "Other",
];

export const DISTRICT_TO_PROVINCE = {
  Achham: "Sudurpashchim",
  Arghakhanchi: "Lumbini",
  Baglung: "Gandaki",
  Baitadi: "Sudurpashchim",
  Bajhang: "Sudurpashchim",
  Bajura: "Sudurpashchim",
  Banke: "Lumbini",
  Bara: "Madhesh",
  Bardiya: "Lumbini",
  Bhaktapur: "Bagmati",
  Bhojpur: "Koshi",
  Chitwan: "Bagmati",
  Dadeldhura: "Sudurpashchim",
  Dailekh: "Karnali",
  Dang: "Lumbini",
  Darchula: "Sudurpashchim",
  Dhading: "Bagmati",
  Dhankuta: "Koshi",
  Dhanusha: "Madhesh",
  Dolakha: "Bagmati",
  Dolpa: "Karnali",
  Doti: "Sudurpashchim",
  "Eastern Rukum": "Lumbini",
  Gorkha: "Gandaki",
  Gulmi: "Lumbini",
  Humla: "Karnali",
  Ilam: "Koshi",
  Jajarkot: "Karnali",
  Jhapa: "Koshi",
  Jumla: "Karnali",
  Kailali: "Sudurpashchim",
  Kalikot: "Karnali",
  Kanchanpur: "Sudurpashchim",
  Kapilvastu: "Lumbini",
  Kaski: "Gandaki",
  Kathmandu: "Bagmati",
  Kavrepalanchok: "Bagmati",
  Khotang: "Koshi",
  Lalitpur: "Bagmati",
  Lamjung: "Gandaki",
  Mahottari: "Madhesh",
  Makwanpur: "Bagmati",
  Manang: "Gandaki",
  Morang: "Koshi",
  Mugu: "Karnali",
  Mustang: "Gandaki",
  Myagdi: "Gandaki",
  Nawalpur: "Gandaki",
  Nuwakot: "Bagmati",
  Okhaldhunga: "Koshi",
  Palpa: "Lumbini",
  Panchthar: "Koshi",
  Parasi: "Lumbini",
  Parbat: "Gandaki",
  Parsa: "Madhesh",
  Pyuthan: "Lumbini",
  Ramechhap: "Bagmati",
  Rasuwa: "Bagmati",
  Rautahat: "Madhesh",
  Rolpa: "Lumbini",
  Rupandehi: "Lumbini",
  Salyan: "Karnali",
  Sankhuwasabha: "Koshi",
  Saptari: "Madhesh",
  Sarlahi: "Madhesh",
  Sindhuli: "Bagmati",
  Sindhupalchok: "Bagmati",
  Siraha: "Madhesh",
  Solukhumbu: "Koshi",
  Sunsari: "Koshi",
  Surkhet: "Karnali",
  Syangja: "Gandaki",
  Tanahun: "Gandaki",
  Taplejung: "Koshi",
  Terhathum: "Koshi",
  Udayapur: "Koshi",
  "Western Rukum": "Karnali",
};
