export const NEPAL_LOCATION_OPTIONS = [
  {
    province: "Koshi",
    districts: [
      { name: "Bhojpur", cities: ["Bhojpur", "Shadananda", "Hatuwagadhi"] },
      { name: "Dhankuta", cities: ["Dhankuta", "Pakhribas", "Mahalaxmi"] },
      { name: "Ilam", cities: ["Ilam", "Deumai", "Suryodaya"] },
      { name: "Jhapa", cities: ["Bhadrapur", "Mechinagar", "Damak"] },
      { name: "Khotang", cities: ["Diktel", "Halesi", "Rupakot Majhuwagadhi"] },
      { name: "Morang", cities: ["Biratnagar", "Belbari", "Urlabari"] },
      { name: "Okhaldhunga", cities: ["Siddhicharan", "Molung", "Champadevi"] },
      { name: "Panchthar", cities: ["Phidim", "Falelung", "Kummayak"] },
      { name: "Sankhuwasabha", cities: ["Khandbari", "Madi", "Chainpur"] },
      {
        name: "Solukhumbu",
        cities: ["Salleri", "Solu Dudhkunda", "Khumbu Pasanglhamu"],
      },
      { name: "Sunsari", cities: ["Inaruwa", "Itahari", "Dharan"] },
      {
        name: "Taplejung",
        cities: ["Phungling", "Aathrai Tribeni", "Sidingwa"],
      },
      { name: "Terhathum", cities: ["Myanglung", "Laligurans", "Aathrai"] },
      { name: "Udayapur", cities: ["Gaighat", "Triyuga", "Katari"] },
    ],
  },
  {
    province: "Madhesh",
    districts: [
      { name: "Bara", cities: ["Kalaiya", "Simraungadh", "Jitpur Simara"] },
      {
        name: "Dhanusha",
        cities: ["Janakpur", "Mithila", "Ganeshman Charnath"],
      },
      { name: "Mahottari", cities: ["Jaleshwar", "Bardibas", "Gaushala"] },
      { name: "Parsa", cities: ["Birgunj", "Pokhariya", "Parsagadhi"] },
      { name: "Rautahat", cities: ["Gaur", "Chandrapur", "Garuda"] },
      { name: "Saptari", cities: ["Rajbiraj", "Kanchanrup", "Hanumannagar"] },
      { name: "Sarlahi", cities: ["Malangwa", "Haripur", "Lalbandi"] },
      { name: "Siraha", cities: ["Siraha", "Lahan", "Mirchaiya"] },
    ],
  },
  {
    province: "Bagmati",
    districts: [
      {
        name: "Bhaktapur",
        cities: ["Bhaktapur", "Madhyapur Thimi", "Suryabinayak"],
      },
      { name: "Chitwan", cities: ["Bharatpur", "Ratnanagar", "Khairahani"] },
      {
        name: "Dhading",
        cities: ["Dhadingbesi", "Nilkantha", "Benighat Rorang"],
      },
      { name: "Dolakha", cities: ["Charikot", "Bhimeshwor", "Jiri"] },
      { name: "Kathmandu", cities: ["Kathmandu", "Kirtipur", "Tokha"] },
      { name: "Kavrepalanchok", cities: ["Dhulikhel", "Banepa", "Panauti"] },
      { name: "Lalitpur", cities: ["Lalitpur", "Godawari", "Mahalaxmi"] },
      { name: "Makwanpur", cities: ["Hetauda", "Thaha", "Bakaiya"] },
      { name: "Nuwakot", cities: ["Bidur", "Belkotgadhi", "Likhu"] },
      { name: "Ramechhap", cities: ["Manthali", "Ramechhap", "Umakunda"] },
      { name: "Rasuwa", cities: ["Dhunche", "Uttargaya", "Gosaikunda"] },
      {
        name: "Sindhuli",
        cities: ["Kamalamai", "Dudhauli", "Hariharpurgadhi"],
      },
      { name: "Sindhupalchok", cities: ["Chautara", "Melamchi", "Barhabise"] },
    ],
  },
  {
    province: "Gandaki",
    districts: [
      { name: "Baglung", cities: ["Baglung", "Dhorpatan", "Galkot"] },
      { name: "Gorkha", cities: ["Gorkha", "Palungtar", "Sulikot"] },
      { name: "Kaski", cities: ["Pokhara", "Annapurna", "Machhapuchchhre"] },
      { name: "Lamjung", cities: ["Besisahar", "Rainas", "Madhya Nepal"] },
      { name: "Manang", cities: ["Chame", "Nason", "Narpa Bhumi"] },
      { name: "Mustang", cities: ["Jomsom", "Gharpajhong", "Thasang"] },
      { name: "Myagdi", cities: ["Beni", "Malika", "Mangala"] },
      { name: "Nawalpur", cities: ["Kawasoti", "Devchuli", "Madhyabindu"] },
      { name: "Parbat", cities: ["Kusma", "Phalebas", "Jaljala"] },
      { name: "Syangja", cities: ["Putalibazar", "Waling", "Bhirkot"] },
      { name: "Tanahun", cities: ["Damauli", "Byas", "Shuklagandaki"] },
    ],
  },
  {
    province: "Lumbini",
    districts: [
      {
        name: "Arghakhanchi",
        cities: ["Sandhikharka", "Sitganga", "Bhumikasthan"],
      },
      { name: "Banke", cities: ["Nepalgunj", "Kohalpur", "Rapti Sonari"] },
      { name: "Bardiya", cities: ["Gulariya", "Madhuwan", "Rajapur"] },
      { name: "Dang", cities: ["Tulsipur", "Ghorahi", "Lamahi"] },
      {
        name: "Eastern Rukum",
        cities: ["Rukumkot", "Putha Uttarganga", "Sisne"],
      },
      { name: "Gulmi", cities: ["Tamghas", "Resunga", "Musikot"] },
      { name: "Kapilvastu", cities: ["Taulihawa", "Kapilvastu", "Banganga"] },
      { name: "Palpa", cities: ["Tansen", "Rampur", "Rainadevi Chhahara"] },
      { name: "Parasi", cities: ["Ramgram", "Sunwal", "Bardaghat"] },
      { name: "Pyuthan", cities: ["Pyuthan", "Sworgadwari", "Mandavi"] },
      { name: "Rolpa", cities: ["Liwang", "Rolpa", "Triveni"] },
      { name: "Rupandehi", cities: ["Butwal", "Siddharthanagar", "Tilottama"] },
    ],
  },
  {
    province: "Karnali",
    districts: [
      { name: "Dailekh", cities: ["Dailekh", "Dullu", "Gurans"] },
      { name: "Dolpa", cities: ["Dunai", "Thuli Bheri", "Tripurasundari"] },
      { name: "Humla", cities: ["Simikot", "Namkha", "Sarkegad"] },
      { name: "Jajarkot", cities: ["Khalanga", "Bheri", "Chhedagad"] },
      { name: "Jumla", cities: ["Jumla", "Chandannath", "Tatopani"] },
      { name: "Kalikot", cities: ["Manma", "Khandachakra", "Tilagupha"] },
      { name: "Mugu", cities: ["Gamgadhi", "Chhayanath Rara", "Soru"] },
      { name: "Salyan", cities: ["Salyan", "Sharada", "Bagchaur"] },
      {
        name: "Surkhet",
        cities: ["Birendranagar", "Bheriganga", "Panchapuri"],
      },
      { name: "Western Rukum", cities: ["Musikot", "Aathbiskot", "Banphikot"] },
    ],
  },
  {
    province: "Sudurpashchim",
    districts: [
      { name: "Achham", cities: ["Mangalsen", "Sanfebagar", "Kamalbazar"] },
      { name: "Baitadi", cities: ["Dasharathchand", "Patan", "Purchaudi"] },
      { name: "Bajhang", cities: ["Chainpur", "Jayaprithvi", "Bungal"] },
      { name: "Bajura", cities: ["Martadi", "Badimalika", "Budhinanda"] },
      { name: "Dadeldhura", cities: ["Dadeldhura", "Amargadhi", "Parashuram"] },
      { name: "Darchula", cities: ["Darchula", "Mahakali", "Shailyashikhar"] },
      { name: "Doti", cities: ["Dipayal", "Silgadhi", "Shikhar"] },
      { name: "Kailali", cities: ["Dhangadhi", "Tikapur", "Lamki"] },
      { name: "Kanchanpur", cities: ["Bhimdatta", "Shuklaphanta", "Punarbas"] },
    ],
  },
];

export const FREELANCER_SKILL_GROUPS = [
  {
    label: "Development",
    options: [
      "Full-Stack Development",
      "Frontend Development",
      "Backend Development",
      "Mobile App Development",
      "WordPress Development",
      "Ecommerce Development",
      "API Integration",
      "QA & Testing",
    ],
  },
  {
    label: "Design & Creative",
    options: [
      "UI/UX Design",
      "Graphic Design",
      "Logo Design",
      "Brand Identity",
      "Video Editing",
      "Motion Graphics",
      "Presentation Design",
      "Illustration",
    ],
  },
  {
    label: "Marketing & Growth",
    options: [
      "Digital Marketing",
      "Social Media Management",
      "SEO",
      "Content Marketing",
      "Email Marketing",
      "Paid Ads",
      "Lead Generation",
      "Sales Funnel Setup",
    ],
  },
  {
    label: "Writing & Support",
    options: [
      "Content Writing",
      "Copywriting",
      "Technical Writing",
      "Translation",
      "Virtual Assistance",
      "Customer Support",
      "Data Entry",
      "Project Coordination",
    ],
  },
];

export const FREELANCER_TAG_OPTIONS = [
  "Remote Ready",
  "Verified Portfolio",
  "Quick Turnaround",
  "Client Communication",
  "Long-Term Projects",
  "Startup Experience",
  "Agency Experience",
  "Problem Solver",
  "Detail Oriented",
  "Available This Week",
  "Weekend Availability",
  "English Fluent",
  "Nepali Fluent",
  "Revisions Included",
  "Brand Strategy",
  "Figma Expert",
  "React Specialist",
  "Node.js Specialist",
  "Shopify Ready",
  "SEO Focused",
];

export const FREELANCER_LANGUAGE_OPTIONS = [
  "Nepali",
  "English",
  "Hindi",
  "Newari",
  "Maithili",
  "Bhojpuri",
  "Tamang",
];
