export const JOB_STATUS = {
  DRAFT: "DRAFT",
  OPEN: "OPEN",
  BOOKING_PENDING: "BOOKING_PENDING",
  CONTRACT_PENDING: "CONTRACT_PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const BOOKING_STATUS = {
  PENDING: "PENDING",
  VISIT_OTP_PENDING: "VISIT_OTP_PENDING",
  VISIT_VERIFIED: "VISIT_VERIFIED",
  QUOTED: "QUOTED",
  CONTRACT_CREATED: "CONTRACT_CREATED",
  CANCELLED: "CANCELLED",
};

export const PROPOSAL_STATUS = {
  PENDING: "pending",
  ACCEPTED: "accepted",
  REJECTED: "rejected",
  WITHDRAWN: "withdrawn",
};

export const CANCELLATION_STATUS = {
  NONE: "NONE",
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
};

export const MILESTONE_STATUS = {
  ACTIVE: "ACTIVE",
  SUBMITTED: "SUBMITTED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const CONTRACT_STATUS = {
  DRAFT: "DRAFT",
  PENDING_FREELANCER_SIGNATURE: "PENDING_FREELANCER_SIGNATURE",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const CONTRACT_TYPE = {
  FULL_PROJECT: "full_project",
  MILESTONE_BASED: "milestone_based",
};

export const DISPUTE_STATUS = {
  OPEN: "OPEN",
  UNDER_REVIEW: "UNDER_REVIEW",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
};

export const CONTRACT_FUNDING_STATUS = {
  UNFUNDED: "UNFUNDED",
  FUNDED: "FUNDED",
  PARTIALLY_RELEASED: "PARTIALLY_RELEASED",
  RELEASED: "RELEASED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
  REFUNDED: "REFUNDED",
};
